import { Urbanist } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";
import 'primereact/resources/themes/lara-light-indigo/theme.css'; 

const urbanist = Urbanist({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-urbanist',
  // You can specify weights like this:
  weight: ['100','200','300', '400', '500', '600', '700', '800', '900'],
});


export const metadata = {
  title: "Bankerslub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
